name: .NET Build and Test

on:
  push:
    branches:
      - '**'

jobs:
  build-and-test:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Restore packages
      run: dotnet restore

    - name: Build solution
      run: dotnet build --no-restore --configuration Release

    - name: Run unit tests
      run: dotnet test --no-build --verbosity normal

    - name: Check which bash is being used
      shell: cmd
      run: where bash

    - name: Check Git Bash via PowerShell
      shell: powershell
      run: |
        & "C:\Program Files\Git\bin\bash.exe" -c "echo Git Bash is working! && bash --version"

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.DEPLOY_KEY }}

    - name: Deploy to VPS via Git Bash
      shell: powershell
      run: |
        & "C:\Program Files\Git\bin\bash.exe" -c "
          ssh -o StrictHostKeyChecking=no root@192.168.214.98 'bash /var/www/sourceexample/deploy.sh'
        "

    

