name: .NET Build and Test

on:
  push:
    branches:
      - '**'

jobs:
  build-and-test:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Restore packages
      run: dotnet restore

    - name: Build solution
      run: dotnet build --no-restore --configuration Release

    - name: Run unit tests
      run: dotnet test --no-build --verbosity normal

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.DEPLOY_KEY }}
    
    - name: Deploy to VPS
      run: |
        ssh -t -o StrictHostKeyChecking=no root@192.168.214.99 << 'EOF'
          cd /var/www/sourceexample
          git pull origin main
          dotnet publish -c Release -o publish
          # Run hoặc restart app
          pkill -f sourceexample.dll || true
          nohup dotnet ./publish/sourceexample.dll > log.txt 2>&1 &
        EOF
